name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up C++
        uses: actions/setup-cmake@v1
      - name: Compile library
        run: cmake .
        run: make
      - name: Run tests
        run: ./tests
