name: Test C++ Library
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
      - name: Build library
        run: |
          cmake lib
          make
      - name: Set up Python environment
        run: |
          python3 -m venv venv
          venv/bin/pip install pytest
      - name: Test library
        run: |
          venv/bin/pytest tests/
    environment:
      PATH:./lib
