name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Install C++ compiler
        run: sudo apt-get install g++

      - name: Compile library
        run: cd lib && cmake . && make

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        run: sudo apt-get install python3-pip

      - name: Install PyTest
        run: pip3 install pytest

      - name: Check library status
        run: echo $LIBRARY_STATUS

      - name: Run tests
        run: pytest tests
