name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up C++
        uses: actions/setup-cmake@v1
        with:
          cmake-version: 3.20.0

      - name: Compile library
        run: cd lib && cmake . && make

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cd lib && ./tests
