name: Build C++ Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ compiler
        uses: actions/setup-cpp@v2
        with:
          cpp-version: '17'

      - name: Build C++ library
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Add additional steps as needed, such as running tests or creating artifacts
